version: "3.3"
services:
  scrutinize:
    image: bdillmann/scrutinize:latest
    ports:
      - "5001:80"
    environment:
      SCRUTINIZE_DB_HOST: db
    depends_on:
      - db

  db:
    expose:
      - "5432"
    image: postgres:13.1-alpine
    environment:
      POSTGRES_DB: "scrutinize"
      POSTGRES_PASSWORD: "password"
      POSTGRES_HOST_AUTH_METHOD: "trust"

  migrador:
    image: bdillmann/scrutinize-migrador:latest
    environment:
      SCRUTINIZE_DB_HOST: db
    depends_on:
      - db
